name: PR comment test

on:
  push:
  workflow_call:

jobs:
  pr_comment_test:
    name: pr_command_help
    runs-on: ubuntu-latest
    steps:
      - name: comment message
        run: |
          wget --quiet https://github.com/kishaningithub/randomtext/releases/download/v1.2.1/randomtext_1.2.1_linux_amd64.deb
          sudo dpkg -i randomtext_1.2.1_linux_amd64.deb
          
          echo "Available commands (300 KB)" > pr-comment.txt
          randomtext -size 300KB -type words >> pr-comment.txt

          du -sh pr-comment.txt

      - name: Post apply output to GitHub PR
        uses: mshick/add-pr-comment@v2
        with:
          allow-repeats: true
          message-path: "pr-comment.txt"
